- server/preprocessing/other-scripts/pubmed.R
@pkraker let me know what you think. 
* url is to the NCBI landing page for the article using the PMID - do you want the landing page to be the publisher's page? if so, they don't give that, but we could just use doi.org + doi 
* i added `date` and `year` fields since you had a field `year`, but I think you had a full date in there, so i added sep. fields for full date and just year
* it's a bit messier than PLOS as we have to parse XML, but it's i think still somewhat fast
> #40 added code for pubmed search

- doc/server_config.md
- server/preprocessing/other-scripts/vis_layout.R
* reworked missing keyword routine: now cleaner and returning better keywords
* added TF-IDF cluster naming based on titles, keywords, and their bi/trigrams
* added cascading filter from longer to shorter ngrams
* formatting gets lost, so included simple first-letter uppercasing
* some old code removed
* tested only locally, result for "natural language processing" on pubmed attached
[natural language processing_pubmed_ntn_clustering.pdf](https://github.com/OpenKnowledgeMaps/Headstart/files/791844/natural.language.processing_pubmed_ntn_clustering.pdf)
> Clusternaming

- vis/js/list.js
- vis/js/papers.js
- vis/stylesheets/base/_colors.scss
- vis/stylesheets/modules/list/_entry.scss
- vis/stylesheets/modules/map/_papers.scss
- vis/templates/list/list_entry.handlebars
- vis/templates/map/paper.handlebars
WIP.
Paper open data icon:
TODO:
> [WIP] Replace open access icon with open data icon for datasets

- server/preprocessing/other-scripts/rplos.R
- server/preprocessing/other-scripts/rplos_fast.R
Hello!
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that recommendation by changing all static DOI links, as well as code that generates new ones.
Cheers :-)
> link DOIs to preferred resolver

- doc/server_config.md
- server/preprocessing/other-scripts/altmetrics.R
- server/preprocessing/other-scripts/base.R
- server/preprocessing/other-scripts/openaire.R
- server/preprocessing/other-scripts/test/base-test.R
- server/preprocessing/other-scripts/test/doaj-test.R
- server/preprocessing/other-scripts/test/pubmed-test.R
- server/preprocessing/other-scripts/test/rplos_fast-test.R
- server/preprocessing/other-scripts/test/test-openaire.R
- server/preprocessing/other-scripts/text_similarity.R
- server/preprocessing/other-scripts/utils.R
- server/preprocessing/other-scripts/vis_layout.R
* some package restructuring: reused utility functions moved into utils.R
* added altmetrics through integration of rAltmetric as far as available
* note: doi-updates #207 already merged into this PR
* metrics have been added to the output_json under following keys: 'cited_by_tweeters_count', 'readers.mendeley', 'citation_count'
inspect by running test-openaire.R and then
```
output <- fromJSON(output_json)
output[c('title', 'doi', 'cited_by_tweeters_count', 'readers.mendeley', 'citation_count')]
1 - colSums(mapply(is.na, output[c('cited_by_tweeters_count', 'readers.mendeley', 'citation_count')]))/nrow(output)
```
for exemplary data and basic statistics on coverage
> VIPER metrics

- server/services/searchOpenAire.php
* Change q to acronym for clarity
* Change funding_level to funder in order to correspond with R scripts
* Add all project details required to populate 'more info' in headstart
Depended on by: #215 and #217
> Update OpenAire service parameters to fit with backend

- vis/stylesheets/modules/map/_header.scss
Set the modals div style to have a relative position and
z-index: 3 so it floats above the map and is still clickable when zoomed
in.
This is consistent with the fix for subdiscipline_title introduced by
ba441853
> Make link and edit modal buttons clickable in zoomed mode

- vis/js/canvas.js
To stop some odd margins appearing that we don't want hide them
with .hide() if the config variables they are set from in canvas.js
are false
> Hide unused context elements

- vis/js/papers.js
- vis/templates/map/paper.handlebars
Short fix to now hide correct element after new id implemented for rounded border for dataset implemented.
Also: Refactor to remove commented code from template to improve clarity
> Hide dataset icons on papers on map when not a dataset

- vis/js/canvas.js
Shrink the chart size by the height of the scale tool bar to ensure
it is visible to users on first glance.
Done by shrinking canvas.available_height consistent with the way
it is shrunk for subtitle_height.
Also refactor to remove typo in 'subtitle_heigth'.
> Make scale toolbar visible above the fold

- examples/viper/data-config_openaire.js
- vis/js/default-config.js
- vis/js/list.js
- vis/js/mediator.js
- vis/templates/list/list_explorer.handlebars
- vis/templates/list/sort_dropdown_entry.handlebars
- vis/templates/misc/scale_toolbar.handlebars
Add new config variable 'sort_menu_dropdown' with default of false
set to true in openaire config.
Add conditional section to list_explorer.handlebars. If
sort_menu_dropdown is true show bootstrap dropdown in place
of radio buttons.
in list .js rename addSortOption to addSortOptionButton for existing
functionality. Introduce new addSortOptionDropdownEntry.
Add "citations" as a sort type for viper and localisation too.
Small refactoring of template + localisation to aid clarity.
>  Sort with dropdown not buttons

- examples/viper/data-config_openaire.js
- vis/js/default-config.js
- vis/js/list.js
- vis/js/mediator.js
- vis/stylesheets/modules/list/_header.scss
- vis/templates/list/filter_dropdown_entry.handlebars
- vis/templates/list/list_explorer.handlebars
- vis/templates/list/show_hide_label.handlebars
Everything in #237 but also fix for the bug @pkraker found.
Also includes header item count. This is done by working through the list, filtering for those items that "should" be in the current view and then counting those that are not marked as filtered_out: true
The implementation is rather ugly because determining what "should" be in the current view is determined after the transition.
Since I was pushed for time and couldn't see a better way to figure out either what the transition was or when it would finish it simply has a "magic" number wait.
You can therefore mess with it by transitioning very quickly.
It would be nicest to have another field in the data for example, "is_visible" which we toggle as zooming in and out.
> Refactoring of Filtering, Implement Filter dropdown and header item count

- vis/js/list.js
As you can see I just poked a single magic number.
Looks like it was originally introduced more than a year ago.
I imagine this is some function of the css and thus might need another poke after Maxi has done up the padding.
> fix scale toolbar gap

- server/preprocessing/other-scripts/openaire.R
Erroneously only the first author per publication was retrieved, now a list of all authors is retrieved and added as a semi-colon separated list. Fixes #250
> fixed #250; now correctly retrieves list of authors

- server/preprocessing/other-scripts/preprocess.R
When too many languages are detected previously, the encoder breaks due to a too low threshold.
> critical preprocessing bugfix

- server/preprocessing/other-scripts/base.R
- server/preprocessing/other-scripts/pubmed.R
- server/preprocessing/other-scripts/test/base-snapshot-ger.R
- server/preprocessing/other-scripts/test/base-snapshot.R
- server/preprocessing/other-scripts/test/base-test-ger.R
- server/preprocessing/other-scripts/test/base-test.R
- server/preprocessing/other-scripts/test/create_snapshots.R
- server/preprocessing/other-scripts/test/pubmed-snapshot.R
- server/preprocessing/other-scripts/test/pubmed-test.R
- server/preprocessing/other-scripts/test/test-openaire.R
- server/preprocessing/other-scripts/text_similarity.R
This PR fixes two aspects in our logging system:
* The tests now more closely mirror the logging output in production: The get_papers method and the vis_layout method have been wrapped by error loggers
* The logging output for get_papers and vis_layout has been fixed, previously it was
```
2018-09-21 09:37:13 ERROR:ts:Query failed: "informal learning"+""cognitive load"+"augmented reality" 1665-01-01 Error in matrix(nrow = length(res$dcdocid)): data is too long
2018-09-21 09:37:13 ERROR:ts:Query failed: "informal learning"+""cognitive load"+"augmented reality" 2018-09-21 Error in matrix(nrow = length(res$dcdocid)): data is too long
2018-09-21 09:37:13 ERROR:ts:Query failed: "informal learning"+""cognitive load"+"augmented reality" 121 Error in matrix(nrow = length(res$dcdocid)): data is …
```
> Logging fixes

- server/preprocessing/other-scripts/base.R
For BASE get_papers now stops execution when no results have been returned by the API, and returns an error message to `text_similarity`.
> fixed #290

- server/preprocessing/other-scripts/vis_layout.R
Now leaves vis_layout early if no input_data exists, returns an error to text_similarity.
> fixed #291

- server/preprocessing/other-scripts/cluster.R
In the rare cases when only 1 paper is returned, clustering fails. This is now handled explicitly and an error returned to text_similarity.
Please merge after #295 and #296 , as this error handling will only become apparent when the previous ones are handled correctly.
> fixed #292

- server/preprocessing/other-scripts/base.R
- server/preprocessing/other-scripts/text_similarity.R
- server/preprocessing/other-scripts/utils.R
- server/services/searchBASE.php
This PR removes the previously introduced but currently unused parameter lang_id from BASE.
* lang_id removed from searchBASE.php -> This for the moment restores compatiliby with legacy map-id generation
* the lang_id validation function in text_similarity and base.R have been robustified. the if-check for parameter presence now reliably returns a boolean value
* fallback is still all/english
> removed lang_id from BASE params; robustified lang_id mapping

- examples/linkedcat/index.html
- examples/linkedcat/search.js
- server/preprocessing/other-scripts/linkedcat.R
- server/preprocessing/other-scripts/preprocess.R
- server/preprocessing/other-scripts/summarize.R
- server/preprocessing/other-scripts/test/linkedcat-test.R
- server/preprocessing/other-scripts/test/params_linkedcat.json
- server/services/searchLinkedCat.php
Regarding input data:
* the used fields have been adapted to the new SOLR fields
* the text_content used for text_similarity has been reduced to the ocrtext only, since the other fields currently rarely contribute valuable information in that regard
Regarding query functionality:
* the return fields have been specified
* the pub_year filter has been updated to the new SOLR field
* two filter params haven added for inclusion or exclusion of document types (`content_type_a`), queries also work if none of them are specified
Regarding summarization:
* now-defunct conditional lowercasing has been removed as this functionality is superceded by the keyword case-matching
Regarding interaction with external queries:
* params are now expected to include `exclude_content_type` and …
> Linkedcat backend

- server/preprocessing/other-scripts/test/base-test.R
- server/preprocessing/other-scripts/test/pubmed-test.R
- server/preprocessing/other-scripts/test/test-openaire.R
- server/preprocessing/other-scripts/text_similarity.R
- server/preprocessing/other-scripts/utils.R
- server/services/search.php
So far, when the backend processing fails (either due to input data or a processing problem), no output is returned, and we communicate a general purpose message to the user. This PR implements basic heuristics to detect the most common reasons for failing queries/map generation. This allows to give users better feedback about why queries failed, and allows us to give users suggestions for more successful queries.
Process:
* Instead of returning nothing, the R-backend now runs an error detection heuristic (utils.R, detect_error) and returns a json, for example `{"reason":"probably timeframe too short","message":"No input data found.","status":"error"}`
* The search.php service has been modified to check the output of the call to the R-backend, if the json contains a `status == error`, it …
> Error handling

- server/services/getLinkedCatAuthors.php
This PR
* fills the image_link placeholder with data from the `author100_wiki_img` SOLR field, an array for an author now looks like `["(DE-588)116506067","Chmel, Joseph",78,"1798-1858","http:\/\/commons.wikimedia.org\/wiki\/Special:FilePath\/Joseph%20Chmel.jpg"]`
* if the field is empty, the placeholder `""` remains
* additionally, the handling of non-200 returns is improved, and failed URLs returned to the queue
> Linkedcat author suggestions

- server/preprocessing/other-scripts/cluster.R
- server/preprocessing/other-scripts/features.R
This PR makes generation of maps with one content item possible. For this three points in the pipeline had to be improved:
* Clustering would fail with one content item. Fallback data have been introduced that emulate a clustering outcome with 1 cluster containing 1 item in `create clusters` and `get_distance_matrix`
* Layout would fail, because the existing function could not correctly produce 2 dimensional coordinates for only 1 item. Fallback data structure was introduced in `get_nmds`
It has been tested with authors with only 1 paper in LinkedCat, and on BASE by shrinking the date range until only 1 paper was returned. Due to broader date indexing in Pubmed, so far no 1 paper map could be tested.
> Fix 1contentmaps

- server/preprocessing/other-scripts/linkedcat_authorview.R
This PR implements the bugfixes from #335 that have been made to the linkedcat-backend also on the authorview-backend. The code diverged here, as a lot of the mapping functionality is shared, but duplicated in both APIs
A redesign and modularisation of functionalities may be advised.
> fixed area inconsistencies between bubble-titles and associated docs

- server/preprocessing/other-scripts/linkedcat.R
- server/preprocessing/other-scripts/linkedcat_authorview.R
This PR
* cleans up separation for keywords and basisklassifikationen
* adds co-authors from `author700_a` to `metadata$authors`, separated by `; `
> add co-authors to authorlist, fix keyword separation

- server/preprocessing/other-scripts/summarize.R
This PR fixes #331 . Previously, basic searches would fail at the summarization stage when filtering stopwords in n-gram title candidates that contain invalid regexes (e.g. `(candidate)`).
The fix replaces grepl with a stringi-function that is more robust to edge cases.
The PR has been tested with searches on the full pipeline on BASE and PubMed for `brown, fbi, red` that previously failed, and a range of other searches that indicated no deterioration.
> robustified stopword filtering in bubble summarization

- doc/server_config.md
- server/classes/headstart/preprocessing/calculation/RCalculation.php
- server/preprocessing/other-scripts/linkedcat.R
- server/preprocessing/other-scripts/linkedcat_authorview.R
- server/preprocessing/other-scripts/streamgraph.R
- server/services/getLatestRevision.php
This PR introduces streamgraph-calculation into the backend.
The calculation is called at the getLatestRevision-stage when the frontend loads a map-representation.
The appropriate function in the frontend needs to set an additional parameter `streamgraph` to true or false, similar how the `context` parameter is set.
If the parameter is true, the JSON-maprepresentation is handed to a new function `performStreamgraphCalculation` in RCalculation.php, which works similar to the existing API routes.
Here a new R-service `streamgraph.R` is called, which creates streamgraph data accordingly to the service - only LinkedCat is currently implemented.
The streamgraph data is then added to the return json which then has following key-value pairs:
```json
{"context": {"k": "v"},
"data": ["list of …
```
> Linkedcat streamgraph backend

- server/preprocessing/other-scripts/summarize.R
This PR fixes #345 , where specific cases of keywords were missing a "-" in bubble titles. For example `Geschichte 1500-1600` would turn into `Geschichte 15001600`.
The tokenization and matching of ngrams has been improved to let `-` characters slip through.
Example on Linkedcat: Author-Overview on "Beidtel, Ignaz"
A few tests on the other pipelines have been conducted and do not show any deterioration. (Improvement is expected but not verified)
> fixed #345 missing "-" in bubble titles

- server/preprocessing/resources/english.stop
This PR fixes #266 by adding "based" to the stopwords-list.
Improvements can be seen by searching for "based" in both PubMed and BASE.
> added 'based' to stopwords

- server/preprocessing/other-scripts/summarize.R
- server/preprocessing/other-scripts/test/base-test-ger.R
- server/preprocessing/other-scripts/test/base-test.R
- server/preprocessing/other-scripts/test/params_linkedcat.json
- server/preprocessing/other-scripts/test/pubmed-test.R
- server/preprocessing/other-scripts/text_similarity.R
- server/preprocessing/other-scripts/vis_layout.R
This PR introduce API-specific summarization:
* a new parameter "api" gets handed down from text-similarity through vis_layout to the cluster-wise summarization procedure
* at this stage it can be decided which tokens are taken into consideration for bubble-titles
* currently only for the linked-cat API a specific route has been implemented, other APIs remain unchanged
* the tests for base and pubmed have been updated to reflect the change in parameters
A few tests have been conducted on base, pubmed which continue to function unchanged; tests on linkedcat show the intended behavior on both authorview and keyword search. for full functionality on linkedcat #347 should be merged as well.
> Linkedcat titleonly

- doc/server_config.md
- server/preprocessing/other-scripts/streamgraph.R
This PR introduces dynamic ranges for the x-axis:
The procedure first looks at the total year-range of the map, if the range exceeds 10 years, the documents are binned into 10 evenly spread time slices. The cut-off value of 10 years and the number of 10 bins has been arbitrarily chosen and can be either changed to a different number, or defined in a dynamic way as well (which needs to be discussed).
The effect can be best seen by comparing an author-streamgraph (e.g. Hammer-Purgstall) with a subject-streamgraph (e.g. "wald").
* requires additional R package: install.packages('forcats')
> Linkedcat streamgraph backend - dynamic ranges

- examples/linkedcat/search_options.js
- server/preprocessing/other-scripts/preprocess.R
- server/preprocessing/other-scripts/text_similarity.R
- server/services/searchLinkedCat.php
This PR adds functionality to create streamgraphs separately from overview maps.
* In the search options, a visualization type selector is re-implemented
* searchLinkedCat now has a vis_type parameter, taken from search_options and relayed to text_similarity
* text_similarity is modified to parse params first, before setting workflow params, as some workflow params will depend on the selected option
* an additional small bugfix for missing keyword replacement has been smuggled in
> Linkedcat keyword streamgraphs

- server/preprocessing/other-scripts/preprocess.R
This PR fixes the occurence of empty bubbles in cases containing only one paper which is additionally missing keywords. Previously, no replacement keywords could be generated as only documents with missing keywords were considered.
Now all documents of a map will be considered for replacement keyword generation (change in L79) while only the documents with missing keywords will be replaced (change in L96).
The effect can be seen in the map for "financial distress" on PubMed with the search range 5 Feb 2019 - 12 Feb 2019.
Additionally, minimal differences may occur in maps with documents which lack keywords, as can be seen in the BASE map of digital education. In general, this may be an improvement, since missing keywords will be replaced with the whole map in mind, leading to them being …
> fixed keyword replacement for single doc bubbles

- server/preprocessing/conf/config.ini
- server/preprocessing/other-scripts/linkedcat_browseview.R
- server/preprocessing/other-scripts/test/linkedcat_browseview-test.R
- server/preprocessing/other-scripts/test/params_linkedcat_browseview.json
- server/preprocessing/other-scripts/text_similarity.R
- server/services/getLinkedCatBrowseTree.php
- server/services/searchLinkedCatBrowseview.php
This PR adds backend and service-layer functionality to
1) create a 2-layer tree of top and lower level document classification, their document counts, and search parameters to create maps
2) search for, and create maps given classification level, a list of classifications, and context parameters
The browseview-tree is cached for 24 hours.
* requires setting a new config parameter (linkedcat_browseview_cache) in config.ini: the location of lc_browseview_cache.json
* adds linkedcat_browseview.R, executing the SOLR search and retrieve
* adds test script and test params
* updates text_similarity.R interface
* adds getLinkedCatBrowseTree.php, which can be called to load from cache or create the browsetree
* adds a search service searchLinkedCatBrowseview.php, which calls the corresponding R …
> Linkedcat browseview backend

- server/preprocessing/other-scripts/preprocess.R
- server/preprocessing/other-scripts/streamgraph.R
- server/preprocessing/other-scripts/summarize.R
- server/preprocessing/other-scripts/utils.R
This PR fixes a browse-view issue where bubble titles like "Über das" appear. The problem is resolved by adding the browseview specific service to some preprocessing and summarization functions.
The difference can be observed on browseview-maps for Geowissenschaften Allgemeines and Rechtsgeschichte.
> added linkedcat_browseview to service-specific functions

- server/preprocessing/other-scripts/linkedcat.R
This PR adds boosting/de-boosting to specific fields for the linkedcat-keyword search.
Boost factors for fields can be manipulated in the boost_factors list, if a field is not present its factor will not be modified. Currently the ocr-fulltext is very strongly deboosted, title strongly boosted and keyword fields slightly boosted.
Locally deployed tests show no changes when search phrase does not appear in title/keywords (e.g. hund/katze/maus);
Overview change when keywords indeed appear in title/keywords and a lot in fulltext, for example: wien, ägypten, sprache;
> Linkedcat search boost factors

- server/services/getLinkedCatAuthors.php
- server/services/getLinkedCatBrowseTree.php
This PR adds the `--force-refresh` commandline/script argument to the scripts that create and update the author-suggest and browsetree cache files.
This is to enable a forced refresh via cron in <24h intervals. Default script calls remain unchanged.
> Linkedcat backend force cache refresh

- server/preprocessing/other-scripts/streamgraph.R
This PR fixes a bug where in rare cases invalid streamgraph data was created, with timeslices receiving a keyword count, but no associated label and no corresponding documents.
Empty metadata, should it appear, will now be replaced with "NA" and filtered out.
Test cases were "wien" and "Ettingshausen, Andreas" where the missing labels were fixed, and authors like Aschbach and Calasanza, where behavior is unchanged.
> fix empty streamgraph labels

- server/preprocessing/other-scripts/linkedcat.R
- server/preprocessing/other-scripts/linkedcat_authorview.R
- server/preprocessing/other-scripts/linkedcat_browseview.R
This PR fixes a bug where keywords in some cases were incorrectly separated by ";" only, instead of "; ". This also restores desired streamgraph behaviour.
> Linkedcat backend - keyword separation fix

- .gitignore
- server/preprocessing/other-scripts/linkedcat.R
- server/preprocessing/other-scripts/linkedcat_authorview.R
- server/preprocessing/other-scripts/linkedcat_browseview.R
- server/services/getLinkedCatAuthors.php
- server/services/getLinkedCatBrowseTree.php
This PR addresses remaining deployment issues:
* A few hardcoded config files have been moved to environment variables. With this change, R now expects following environment variables either in Renviron.site or the System environment:
```
LINKEDCAT_SOLR = "url"
LINKEDCAT_SOLR_PATH = "solr/path"
LINKEDCAT_SOLR_PORT = "NULL" or port
LINKEDCAT_SOLR_SCHEME = "https" or "http"
```
Additionally, the `linkedcat_solr` setting in config_local.ini now has to point to the full path of the SOLR instance.
* Cache files for authors and the browse tree are now created with a rate limit, and the automatic refreshment has been bumped to 48h to give the cron job enough time.
> Linkedcat backend - config defaults

- examples/linkedcat/browse.php
- examples/linkedcat/building_map.php
- examples/linkedcat/head_headstart.php
- examples/linkedcat/headstart.php
- examples/linkedcat/index.php
- examples/linkedcat/js/search.js
- server/classes/headstart/preprocessing/Snapshot.php
- server/services/getLinkedCatAuthors.php
- server/services/getLinkedCatBrowseTree.php
- server/services/search.php
- server/services/snapshot/data-config_linkedcat.js
- server/services/snapshot/headstart_snapshot.php
This PR fixes the last remaining parameter issues and activates snapshots for Linkedcat.
* linkedcat config added to Snapshot backend
* A new route has been added that passes the vis_type parameter on to the snapshot function, with this snapshots are now also possible for streamgraphs.
* A few other files along the pipeline had to be changed as well (fix variable naming inconsistencies), to ensure that variable names that influence both visualization outcome and URL forwarding follow the same convention. Otherwise the Snapshotting backend would not find the visualization in author mode and browse mode.
Functionality and snapshotting has been tested for author overviews and streamgraphs, keyword overviews and streamgraphs, and browseview maps; by manual search awaiting successful loading, …
> Linkedcat backend - Snapshots

- server/preprocessing/other-scripts/linkedcat.R
This PR improves parsing of multi-word queries, which are now retrieved as "word1 AND word2" on all assigned query fields.
> Linkedcat backend: query parsing

- examples/search_repos/data-config_base.js
- server/preprocessing/other-scripts/base.R
- server/preprocessing/other-scripts/test/base-test.R
- server/preprocessing/other-scripts/test/base_regex_test.R
- server/preprocessing/other-scripts/test/params_base.json
This PR enables all Boolean queries described in the [BASE Interface Guide](https://www.base-search.net/about/download/base_interface.pdf) (see section 4 on page 13) in verbatim mode. The changes have been extensively tested, but further tests would be very useful. Examples include:
* 2019-ncov or sars-cov-2
* (cats and dogs) or (sun and moon)
* research -science
* "knowledge domain visualization" or ("knowledge map" and (research or science))
> Enable Boolean queries for BASE

- server/preprocessing/other-scripts/linkedcat.R
- server/services/search.php
This PR updates keyword searches: Multiple words, exact phrases, and negative keywords are now working as intended. Highlighting of more than one word now also works.
Please compare following maps/streamgraphs:
* Kaiser Leopold I
* "Kaiser Leopold I"
* Kaiser Leopold II
* "Kaiser Leopold II"
* Leopold -Kaiser -II
* hund
* hund wolf
* hund -wolf
* -hund wolf
* Ferdinand Wolf
* "Ferdinand Wolf" 
* "Ferdinand Wolf" Houdene
* "Ferdinand Wolf" -Houdene
* Ferdinand Wolf -Mundart
* Ferdinand Wolf Mundart
> Linkedcat backend - multiword, phrase and negative keyword search

- server/services/getLastVersion.php
- server/services/search.php
- server/services/searchBASE.php
- server/services/searchDOAJ.php
- server/services/searchPLOS.php
- server/services/searchPubmed.php
This PR introduces two changes, which enable users of Head Start to implement a fallback AJAX search request, should the original request to the search*.php service not return (this is for example the case with bad connections):
1. A service getLastVersion.php that returns the last version of a map for a given ID (used to check if a map/a specific revision has been created).
2. Add the ability to provide search.php with a precomputed ID (otherwise, the client does not know, what map ID to check for).
This change was tested with all existing examples.
> Enable a fallback AJAX search request on the client

- examples/triple/config_example.php
- examples/triple/data-config_triple.js
- examples/triple/headstart.php
- examples/triple/search.js
- examples/triple/search_options.js
- examples/triple/search_triple.php
- server/services/getLatestRevision.php
- server/services/searchTRIPLE.php
- server/workers/dataprocessing/src/headstart.py
- server/workers/dataprocessing/src/streamgraph.py
- server/workers/triple/src/search_triple.py
- vis/js/headstart.js
This PR implements streamgraph functionality in the backend, and enables it for the TRIPLE API.
* searchTRIPLE.php now uses vis_type for ID creation
* streamgraph data is now persisted after search, an no longer created at map loading stage (faster for user)
* the url call to getLatestRevision in headstart.js now takes the additional parameter "backend". legacy integrations should not be affected
The TRIPLE example has been adapted:
* search_triple.html has been renamed to search_triple.php for the rudimentary search box
* it now has an alternating checkbox for knowledge map and streamgraph
* it now takes a config.php, with an example config attached
It has been tested for BASE, PubMed, VIPER, and knowledge map and streamgraph examples for TRIPLE.
> Triple streamgraph backend

- vis/app.js
- vis/js/canvas.js
- vis/js/mediator.js
- vis/js/scale.js
Fixes dropdown in local_files.
Probably fixes scaling in Viper.
Prior to the webpack 4 version increase it seems that a single
instance of headstart was used throughout the application.
This seems to have been been possible by manipulating the
headstart alias imported in app.js. It wasn't possible to continue
this pattern with webpack 4. I'm unsure the exact reason why but
doing this is probably not advised anyway.
This patch forces an explict global headstart object and ensures
the callers in mediator, canvas and scale all use it.
This is probably not the ideal solution. It might be better to
instead properly inject headstart into the places that need it.
> Force single instance of Headstart

- server/preprocessing/other-scripts/openaire.R
- server/workers/gsheets/src/search_gsheets.py
- server/workers/triple/src/search_triple.py
This PR add "subject_orig" metadata field to map data delivered by the backend for the data integrations where that field has been missing so far.
> implement subject_orig field where missing

- server/preprocessing/other-scripts/doaj.R
- server/preprocessing/other-scripts/test/doaj-test.R
Addresses "DOAJ integration fails" item in trello. There wasn't a space before the second `AND` of the query so that it ended up as `marketing AND bibjson.year:[1809 TO 2017]AND _exists_:bibjson.abstract` which gave no results
Also, deleted a line of code (see line 34) that wasn't supposed to be there AFAICT.
> fix for doaj source, query needed space between query & "AND"

- package-lock.json
- package.json
This PR updates Head Start JS dependencies via `npm audit fix`. Updates are non-breaking version updates and have been tested on BASE, PubMed, VIPER and CoVis integrations.
> Security updates 2020 06

- .gitignore
- package.json
- vis/test/example.test.js
Adding the `collectCoverage` option to the jest settings to show code coverage. After each run, jest creates an html report and saves it into the `coverage/` directory, so I added this directory to the `.gitignore`.
Adding the config path to the jest settings - before that, files with config imported couldn't be tested. Changed the example test to show it works.
> Add coverage and config import to jest tests

- .gitignore
I have 12 local (untracked) files in my repository and it makes working with git inconvenient. I added those files to .gitignore to solve this.
Later, when the deployment process is simplified, we can remove them again.
> Add local deployment files to .gitignore

- server/search_gsheets.docker
- server/services/updateGSheetsMap.php
- server/workers/gsheets/src/search_gsheets.py
- server/workers/run_gsheets.py
- server/workers/services/src/apis/gsheets.py
This PR enables requesting new map data by comparing a "last_update" parameter with the last known change in the GSheet. The server responds with new mapdata when these two timezone-strings don't match.
They can be call by either a GET request to updateGSheetsMap with a "last_update" parameter, or a command line call with `--last_update`
> enable force update for gsheet integration

- examples/viper/head_viper.php
This PR updates the VIPER example to the current standard by giving it a flexible Matomo site ID with the default value of '1'.
I'm not sure about L207 though, maybe it can be omitted. In any case it also needs to reflect the site_id?
> update logging to current standard

- vis/js/components/ContextLine.js
- vis/js/components/HoverPopover.js
- vis/js/components/SubdisciplineTitle.js
- vis/js/templates/ContextLine.jsx
- vis/test/component/contextline.test.js
- vis/test/snapshot/__snapshots__/contextline.test.js.snap
This PR introduces the popover fix:
- There was a console warning saying the &lt;div&gt; cannot be a descendant of &lt;p&gt;, so I fixed it by moving the popover into a different container. 
- Another issue was that the popovers were originally displayed at right, but after the first refactoring, I had to place them at the bottom. Now they're back at the right side.
> Refactoring 01 (MVP): popover fix

- server/preprocessing/other-scripts/test/base-test.R
- server/preprocessing/other-scripts/test/params_pubmed.json
- server/preprocessing/other-scripts/test/pubmed-test.R
- server/preprocessing/other-scripts/test/test-openaire.R
- server/preprocessing/other-scripts/text_similarity.R
- server/preprocessing/other-scripts/utils.R
- server/preprocessing/other-scripts/vis_layout.R
This PR improves error handling:
* errors are now more cleanly separated between data source/search errors and backend data processing errors: data processing errors are now no longer masked by typo/too specific and for now have a generic reason: 'unexpected data processing error'
* a specific error reason for 502 Bad Gateway errors on PubMed has been added: 'API error: requested metadata size'
* other API errors are for now masked by typo/too specific error, because the error handling in R is clumsy.
> Pubmed error reason

- README.md
- config.example.js
- package-lock.json
- package.json
- webpack.config.js
This PR introduces the support for using `config.js` to set the modern frontend flag.
An example config:
```
module.exports = {
publicPath : "http://localhost:8080/dist/",
skin : "linkedcat",
modernFrontendEnabled : true
};
```
This way, there's no need to set the path variable, simply setting the flag in `config.js` is enough. The flag value can still be overwritten by the path variable value though.
So for example, building with `modernFrontendEnabled : false` and the path variable `MODERN_FRONTEND=true` will resolve to the flag being set to true.
Special cases:
- Building with `modernFrontendEnabled : true` and the path variable `MODERN_FRONTEND=` will resolve to the flag being set to false.
- Building with `modernFrontendEnabled : true` and the path variable not being set at all will …
> Flagging from config.js

- server/preprocessing/other-scripts/base.R
- server/preprocessing/other-scripts/pubmed.R
- each fxn gains a new parameter `retry_opts`
- the `retry_opts` parameter accepts a call to either the `bs_retry_options` or `entrez_retry_options` function from each respective package
- the retry options is a named list and gets passed to either rentrez or rbace to configure retry http settings
- defaults are used for retry options, but can be set by the user on each `get_papers` function call
fix #465
> changes to base and pubmed get_papers methods to use retry

- server/preprocessing/other-scripts/utils.R
- server/workers/triple/src/search_triple.py
This PR adds simple phrase search to the TRIPLE integration and adds a "phrase too long" error if a search that includes a phrase "longer than four words" returns no results.
> phrase too long error

- vis/js/actions/index.js
- vis/js/components/ListToggle.js
- vis/js/intermediate.js
- vis/js/list.js
- vis/js/mediator.js
- vis/js/reducers/index.js
- vis/js/reducers/list.js
- vis/js/templates/ListToggle.jsx
- vis/stylesheets/modules/list/_list-show-button.scss
- vis/templates/list/list_explorer.handlebars
- vis/test/component/listtoggle.test.js
- vis/test/snapshot/__snapshots__/listtoggle.test.js.snap
- vis/test/snapshot/listtoggle.test.js
- vis/test/store/initialize.test.js
- vis/test/store/listtoggle.test.js
This PR introduces the 1st part of the List component refactoring: the refactored toggle subcomponent.
The new code can be tested by building the application with MODERN_FRONTEND=true.
**Main features:**
Redux:
- There are three new actions: TOGGLE_LIST (triggered by clicking the toggle), SHOW_LIST (triggered by mediator e.g. when paper in map is clicked) and SET_ITEMS_COUNT (sets a counter of displayed papers - temporary solution until full data is stored in the redux store).
- New reducer for the list data: it shows that the list toggle reacts to multiple events (initialization, list toggle, showing the list).
Components:
- Simple template ListToggle created. Its container, div id="show_hide_button", has to keep in the handlebars for now, so the onclick events are bound to each element …
> Refactoring (List): toggle

- vis/js/intermediate.js
- vis/js/mediator.js
- vis/js/utils/actionLogger.js
I connected the new code to the mediator.js `record_action` function.
Now the Redux actions are logged using that function.
List of the logged actions:
- ZOOM_IN
- ZOOM_OUT
- HOVER_BUBBLE
- RESIZE
- SHOW_LIST
- TOGGLE_LIST
- SORT
- SEARCH
- FILTER
- HOVER_PAPER
- SELECT_PAPER
- DESELECT_PAPER
- INITIALIZE
> Reimplemented the record action

- vis/js/templates/Paper.jsx
This PR fixes a bug that caused a wrong appearance of the open access icon in a paper.
> Bugfix: OA icon in a small paper

- vis/js/templates/listentry/Comments.jsx
Added a missing space between "by" and "comment author" in Covis.
> Added missing space in the covis comments

- vis/js/reducers/data.js
This PR fixes a bug in old maps that is caused by a different data scheme.
Prior to Oct 2018, area_uri could be also an array, which caused problems in the refactored frontend.
This fix sanitizes the area_uri to string if it's not a string or a number.
> Bugfix: area uri in old maps

- vis/js/components/ModalButtons.js
- vis/js/reducers/misc.js
I moved the modal buttons positioning from the project website repository to Headstart.
This function is still restricted only to .org data integration.
Please merge it together with the PR in the project website repository: https://github.com/OpenKnowledgeMaps/project-website/pull/74
> Added modal buttons positioning

- vis/js/default-config.js
In the Headstart context line, I renamed the data source "TRIPLE" to "GoTriple".
> Renamed TRIPLE to GoTriple

- vis/js/templates/footers/TripleBuiltWith.jsx
I changed the label from _TRIPLE_ to _GoTriple_ in the "built with" footer.
> TRIPLE -> GoTriple in builtwith

- vis/js/templates/footers/StandardBuiltWith.jsx
I fixed the "built with" footer in Safari so the date is displayed there too.
> Proper fix for footer in Safari

- README.md
- examples/local_streamgraph/README.md
- examples/project_website/base.html
- examples/project_website/pubmed.html
- webpack.config.js
On the `npm run`, the whole Headstart folder was served as static, which caused a reload on any file change.
This issue has started happening with the new Webpack - it was either a mistake I made during the migration, or the new Webpack simply doesn't ignore changes on some static-served files, such as _.git_.
I fixed that by setting only the _examples/_ folder as static.
This change doesn't have any impact on the deployment - it affects purely the `npm run` local server.
For the local server, it has one consequence: the local examples are now served on the following adresses:
http://localhost:8080/local_files/
http://localhost:8080/local_streamgraph/
http://localhost:8080/project_website/base.html
http://localhost:8080/project_website/pubmed.html
I added this to the READMEs.
In the main …
> Webpack hot reloading examples

- examples/gsheets/data-config.js
- examples/project_website/data-config_base.js
- examples/project_website/data-config_pubmed.js
- examples/viper/js/data-config_openaire.js
- vis/js/default-config.js
- vis/js/headstart.js
- vis/js/mediator.js
Tracking/analytics functions (writeActionToLog, Google Analytics) were removed from _headstart.js_. It was a dead code anyway.
> Removed remaining legacy tracking code

- vis/js/templates/listentry/AccessIcons.jsx
- vis/js/templates/listentry/Tags.jsx
- vis/stylesheets/modules/list/_entry.scss
- vis/test/snapshot/__snapshots__/list-base.test.js.snap
Paper tags css (in list) needed some adjustments. I united the styles into one common class `paper-tag` and added this class to all tag types (open access, free access, dataset, custom tags).
> Fixed covis/viper tags css

- vis/stylesheets/modules/_footer.scss
I added some CSS breakpoints so the whole footer is always visible also on narrower screens.
> Footer on narrow screens

- server/services/exportMetadata.php
- server/workers/api/src/apis/export.py
This PR gets the export functionality working for Mendeley by
* changing the download file-format from ".bibtex" to ".bib"
* reducing the date information in the "year" field to "yyyy"
> Interface changes export backend

- .gitignore
- vis/js/templates/Paper.tsx
- vis/js/templates/modals/infomodal/OrcidInfo.tsx
- vis/stylesheets/modules/map/_header.scss
- vis/stylesheets/modules/map/_papers.scss
- vis/types/declarations/images.d.ts
Add d.ts file for images importing.
> refactoring: typescript images importing error

- local_dev/searchflow-container/Dockerfile
- local_dev/searchflow-container/local_dev.ini
- server/services/getPDF.php
This change enables logging to STDERR from PHP files in the searchflow container for local dev environments.
> add logging for PHP stderr to searchflow container
