OpenKnowledgeMaps/Headstart

server/preprocessing/other-scripts/vis_layout.R
* now filters out ngrams that already occur as part of longer ngrams
=> R experiments

server/preprocessing/other-scripts/experiments/get_baseline_files.R, server/preprocessing/other-scripts/experiments/run_baseline.R, server/preprocessing/other-scripts/experiments/run_experiment.R
consists of
* script to download baseline sampleset
* script to produce baseline metrics
=> first version of evaluation pipeline

vis/js/list.js, vis/js/mediator.js
+ Fixes #99 (filtering of list while paper selected)
+ Fixes #98 (filtering by year)
+ Some mysterious behaviour for #28. See issue thread
=> Few fixes for minor issues

vis/js/default-config.js, vis/js/io.js, vis/js/list.js, vis/js/mediator.js
Reverts OpenKnowledgeMaps/Headstart#108
=> Revert "Add initializeMissingData method; Add default values to default-confi…"

vis/js/headstart.js, vis/js/mediator.js
Sloppy mistake in the last PR, I'm sorry. This one should work.
=> Add initializeMissingData method, fix previous commit

server/preprocessing/other-scripts/pubmed.R
=> fix to pubmed.R to handle books

vis/js/default-config.js, vis/js/io.js, vis/js/list.js, vis/js/mediator.js
some fixes concerning list-only mode.
=> checking for missing methods and default values per localizations,

server/preprocessing/other-scripts/base.R
#118 point 3: 
> output of bs_search() is now a list to accommodate optional facet output, so just need to change to x$docs to get to the same data.frame as before
=> update bs_search output

LICENSE, server/preprocessing/other-scripts/base.R, server/preprocessing/other-scripts/vis_layout.R
- improved cleaning of base subjects
- improved generation of missing keywords
- bubble titles now max. trigrams
- also includes base-deduplication implementation of #126
=> Base preprocessing

server/preprocessing/other-scripts/base.R
fixes things like `Info:eu-repo/classification/ddc/025.063` or `Engineering ( technology`
=> added some further subject cleaning

vis/js/list.js
This should fix the list title click behaviour. list.setImageForListHolder just returned when a papers wasn't oa.
=> Fix list title click behaviour

server/preprocessing/other-scripts/vis_layout.R
number of clusters was hardcoded
=> bugfix - number of clusters

vis/js/list.js, vis/templates/list/list_entry.handlebars
=> Opencon london icons 2

package-lock.json, vis/js/bubbles.js, vis/js/canvas.js, vis/js/mediator.js, vis/js/papers.js, vis/stylesheets/modules/_map.scss, vis/stylesheets/modules/map/_bubbles.scss, vis/stylesheets/modules/map/_papers.scss, vis/templates/map/paper.handlebars
Issues that I noticed:
-  Zoom in cursor is already triggered at the bounding box of the bubbles (still reflects what a click would do though)
- When zooming out while hovering over a bubble, the cursor goes from zoom out to zoom in (so far so good) but then if you mouse over paper it changes to the default cursor and doesnt stay the zoom in cursor. I tried to work around that but havent found the correct thing so far.
=> #173 Change cursor according to click effect (zoom-in/zoom-out) 

.gitignore, README.md, config.example.js, webpack.config.js
People will need to change also the path to the config file from the webpack file - remove example
=> issue #131 - move publicPath to separate config file

server/preprocessing/other-scripts/openaire.R
=> Openaire - now XML response based

doc/server_config.md, server/preprocessing/other-scripts/openaire.R, server/preprocessing/other-scripts/test/base-test.R, server/preprocessing/other-scripts/test/doaj-test.R, server/preprocessing/other-scripts/test/pubmed-test.R, server/preprocessing/other-scripts/test/rplos_fast-test.R, server/preprocessing/other-scripts/test/test-openaire.R, server/preprocessing/other-scripts/text_similarity.R, server/preprocessing/other-scripts/utils.R, server/preprocessing/other-scripts/vis_layout.R
* integrates rOpenSci rcrossref package
* identifies missing DOIs in publications
* tries to fill missing DOIs through asynchronous calls to Crossref
* uses title matching and a final sanity check via levenshtein edit distance with a max. of 5
=> VIPER - async crossref calls for DOI filling

server/preprocessing/other-scripts/altmetrics.R, server/preprocessing/other-scripts/openaire.R, server/preprocessing/other-scripts/test/params_openaire.json
* now allows for combined search of funder and project_id (grant ID)
* incorporates latest updates from rOpenaire
=> Openaire-search

examples/search_repos/search.js, examples/search_repos/search_openaire.html, examples/search_repos/search_openaire_projects.js, examples/search_repos/spinner.css, server/services/searchOpenAire.php
Improved frontend experience.
Still needs proper UX input but should help us in testing.
Addresses issues made in: #201 
Includes backend commits that are not yet merged. e8cefb5f939d61d5522b774fc7b29c6e1406f83a
=> Viper frontend improved examples

examples/search_repos/data-config_openaire.js, examples/search_repos/search_openaire.html, examples/search_repos/search_openaire_projects.js, server/services/searchOpenAire.php, vis/js/canvas.js, vis/js/intro.js, vis/js/io.js, vis/js/mediator.js, vis/templates/info_modal_content/oa_info_modal.handlebars
Change more info modal to suit VIPER projects and include their details.
Possible ToDo:  Sort out `info` vs `intro` both are used to mean basically the same thing. Might be clearer if we stuck to one. I generally stuck to `info` unless it seemed to conflict with what was there.
=> Viper more info modal

examples/search_repos/data-config_openaire.js, examples/search_repos/search_openaire.html, examples/search_repos/search_openaire_projects.js, server/services/searchOpenAire.php, vis/js/default-config.js, vis/js/io.js, vis/js/mediator.js, vis/js/scale.js, vis/templates/misc/scale_toolbar.handlebars
Scaling by some metrics
Configurable in the headstart config file.
Includes dummy explanations
Depends on some frontend and back end commits that haven't been merged yet.
=> Viper Frontend Metric Scaling

server/preprocessing/other-scripts/vis_layout.R
fixed failure in cases where no num_clusters could be detected conclusively
=> fixed rolling k behavior

examples/viper/data-config_openaire.js, vis/js/canvas.js, vis/stylesheets/components/_buttons.scss, vis/templates/misc/viper_edit_button.handlebars, vis/templates/misc/viper_embed_button.handlebars, vis/templates/misc/viper_share_button.handlebars
Include add2any share button using their script in a new handlebars
template for the purpose.
Append it to the modals div if config option is enabled.
=> Add2Any Share button

examples/viper/data-config_openaire.js, vis/js/default-config.js, vis/js/list.js, vis/templates/list/list_entry.handlebars, vis/templates/list/viper_metrics.handlebars
Enabled by a config option and localisation for strings.
A span stored in a new handlebars template. Should be simple to style
or add new classes to add more detailled style if required.
=> Show tweets, readers and citations in list

examples/viper/data-config_openaire.js, vis/js/default-config.js, vis/js/list.js, vis/stylesheets/modules/list/_entry.scss, vis/templates/list/list_entry.handlebars, vis/templates/list/viper_outlink.handlebars
add config option to enable
localise 'link'
handlebars template for each outlink span
=> Add DOI or Link to List entry

examples/viper/data-config_openaire.js, vis/js/bubbles.js, vis/js/list.js, vis/js/mediator.js
Had to add a zoomin_complete method.
Also had to set current_enlarged_paper when clicked in the bubble
not just the list.
Also unset it when clicking in current bubble
Also fire on "zoom" even if no transition has to happen.
=> Fix 243 by calling count from mediator in correct places

server/preprocessing/other-scripts/vis_layout.R
=> robustified elbow_k method

examples/viper/data-config_openaire.js, vis/js/mediator.js, vis/templates/misc/scale_toolbar.handlebars
Add new config variable viper_credit.
Pass variable to scale_toolbar
Add handlebars 'if clause' to scale_toolbar.handlebars
=> Make credit togglable from config variable

examples/viper/headstart.php, vis/js/canvas.js
if &embed=true is passed then hide the footer and set
viper_credit=true in the config.
This can then be used to display the credit image
=> Param in headstart.php for embed mode

server/preprocessing/other-scripts/features.R, server/preprocessing/other-scripts/summarize.R, server/preprocessing/other-scripts/vis_layout.R
Partially implements #284 but only to the point where the first, most common variant is taken.
=> fixed upper-lowercasing of bubble titles

server/preprocessing/other-scripts/summarize.R
the forgotten commit in addition to #307, removing the deprecated tolower-flag
=> remove deprecated tolower-flag

server/preprocessing/other-scripts/linkedcat.R, server/preprocessing/other-scripts/preprocess.R, server/preprocessing/other-scripts/utils.R
* added dev-flag for highlights
* reduced summarization to title and keyword_a
* fixed german stopword problem
=> Linkedcat backend

server/preprocessing/other-scripts/linkedcat.R
* highlights now separated by ` ... `
=> new highlight separation

server/preprocessing/other-scripts/streamgraph.R
With this PR the streamgraph-data has been simplified again, since functionality of binning moved to the frontend.
* there is no longer a separate handling and binning needed for streamgraph-timeseries that are longer than a hardcoded threshold
* unused associated functionality was removed
Tested on maps for Hammer-Purgstall, Calasanza, Brücke, Pfizmaier, and also verified that filling up of missing yearly data still works (see map for Firnhaber).
=> simplified streamgraph x-axis binning

package.json
Temporary fixes #263 until #363 is approved.
Tested on a clean git clone with `npm install` and `npm run dev/prod/start`.
=> clean-webpack-plugin version hotfix

examples/cris_vis/data/final_output2_de.json, examples/cris_vis/data/final_output2_en.json
* changed bubble titles in de/en file
* reassigned question in de/en file
tested locally
=> crisvis2 data update

server/preprocessing/other-scripts/linkedcat.R, server/preprocessing/other-scripts/linkedcat_authorview.R, server/preprocessing/other-scripts/linkedcat_browseview.R
This PR fills the last remaining metadata gap with the newly added field for goobi_links.
=> goobi_link to PDF added

server/preprocessing/other-scripts/linkedcat_browseview.R
This PR fixes a query builder bug where queries for sub-bkl failed.
=> browseview search fix

examples/cris_vis/data/final_output2_de.json, examples/cris_vis/data/final_output2_en.json
* Changed english cluster name from Impacts to Implications as requested
=> changed english cluster name

server/preprocessing/other-scripts/linkedcat.R, server/preprocessing/other-scripts/linkedcat_authorview.R, server/preprocessing/other-scripts/linkedcat_browseview.R
Fixes the rare case that the keyword_label field is NA.
=> linkedcat: keyword error handling and cleaning

server/preprocessing/other-scripts/linkedcat.R
This PR should address the last remaining instances of wrongly highlighted tokens.
=> Linkedcat more regex fixing

server/preprocessing/other-scripts/linkedcat.R
Reverts OpenKnowledgeMaps/Headstart#415
=> Revert "Linkedcat backend: query parsing"

server/preprocessing/other-scripts/pubmed.R
=> remove slashes pubmed queries

server/preprocessing/other-scripts/pubmed.R
This PR fixes a minor formatting issue with keyword separation in the PubMed integration.
=> keyword separators fixed

server/preprocessing/other-scripts/openaire.R
This PR fixes the issue with diverging document counts between the suggestion (correct) and actual map count (so far, too few).
=> fix openaire integration

server/search_triple.docker, server/workers/requirements.txt, server/workers/triple/requirements.txt, server/workers/triple/src/search_triple.py
This PR adds language data enrichment for title and abstract fields and a language-based content filter; if no language (or all) is chosen English is preferred, if English is not present the longest segment is preferred.
=> language detection for metadata fields

vis/js/default-config.js, vis/js/io.js, vis/js/list.js
This PR fixes two bugs:
* highlighted text sorted above unhighlighted text
* undefined query highlights
=> Fix sort highlight bug

examples/search_repos/search_options.js
This PR updates the search options for the BASE example to the current status.
=> base search options update

server/preprocessing/other-scripts/preprocess.R, server/preprocessing/other-scripts/text_similarity.R, server/preprocessing/other-scripts/vis_layout.R
This PR improves backend behavior in edge cases where paper_abstract is extremely long, hardcoded to >17.000 characters.
=> Abstract sanitization

server/services/search.php, server/services/searchTRIPLE.php
This PR fixes a highlighting issue that surfaced in the TRIPLE data integration.
=> Triple highlighting backend

package-lock.json, package.json, server/preprocessing/other-scripts/preprocess.R, server/preprocessing/other-scripts/summarize.R, server/preprocessing/other-scripts/utils.R
This PR includes
* summarization bugfixes (occurrence of "????" as bubble titles)
* better error detection and handling for the PubMed integration
* a minor frontend security update
=> Maintenance update 2020-12

server/preprocessing/other-scripts/base.R, server/preprocessing/other-scripts/openaire.R, server/preprocessing/other-scripts/test/base-test.R, server/workers/services/src/apis/persistence.py, server/workers/services/src/database.py
This PR implements a few bugfixes for the backend-pipeline:
* metadata-schema alignment for BASE
* bugfix for OpenAIRE/VIPER
* bugfix for postgresql-persistence API
=> Backend maintenance

server/services/searchTRIPLE.php, server/workers/services/src/apis/triple.py
Integrate triple error message with existing response data formats
=> Search flow integration backend

vis/js/reducers/localization.js
I added a missing loading label in covis - something that I broke during the final refactoring step.
=> Bugfix: loading in Covis

examples/viper/js/search_openaire_projects.js, server/services/getOpenAireProjects.php, server/services/getOpenAireTotals.php
Make error text slightly more expressive and change API requests from http to https
=> Viper errortext

package-lock.json, package.json, webpack.config.js
* npm audit fix
* removed some unused packages for remaining issues
=> security update 2021-06

examples/local_files/index.html
I broke the local files example with the PR #551 so this branch fixes it by adding jQuery CDN into the local files outer page.
=> Local files example jQuery

vis/js/components/Heading.js, vis/js/default-config.js, vis/js/templates/ZoomedOutHeading.jsx
- renamed _Source_ to _Data source_ in all integrations
- showing _Data source: TRIPLE_ in TRIPLE
- hiding info dialog button in TRIPLE
=> Data source + info button

examples/triple/.gitignore, examples/triple/config_searchflow.php, vis/js/templates/CreatedBy.jsx
Please merge this PR together with or after search-flow PR 5 (https://github.com/OpenKnowledgeMaps/search-flow/pull/5).
This PR introduces forced embed mode in TRIPLE visualizations.
=> Forcing embed mode in triple

examples/gsheets/index.php
In gsheets example there was an old reload button that caused problems during the deployment. I removed it.
=> Removed reload button from gsheets

vis/js/components/Footer.js, vis/js/intermediate.js, vis/js/reducers/data.js, vis/js/reducers/index.js, vis/js/utils/data.js, vis/test/store/data.test.js
With the recent changes ([Streamgraph frontend adaptations](https://github.com/OpenKnowledgeMaps/Headstart/pull/568), [Builtwith footer refactoring](https://github.com/OpenKnowledgeMaps/Headstart/pull/570)) I somehow broke the local files example.
This PR fixes the bugs.
=> Local files fix

vis/js/templates/footers/StandardBuiltWith.jsx
Attempt to fix the error in Safari.
=> Safari footer date format fix

CHANGELOG.md, vis/js/utils/dimensions.js, vis/stylesheets/modules/_footer.scss, vis/stylesheets/modules/map/_header.scss
- unified HTML & CSS of various paper tags (access tags, dataset tag, custom tags)
=> Biweekly release (21-12-22)

vis/js/default-config.js, vis/js/reducers/list.js, vis/js/templates/listentry/PaperButtons.jsx
The cite feature was disabled for now and can be enabled by the config parameter `cite_papers`.
=> Disabled cite feature

package-lock.json
Updated npm dependencies with `npm audit fix`.
=> Security update 2022-02

CHANGELOG.md
=> Biweekly release (22-03-03)

vis/js/reducers/timespan.js, vis/stylesheets/base/_colors.scss, vis/stylesheets/modules/list/_entry.scss
GoTriple CSS changes and timespan settings.
=> GoTriple final review changes

package-lock.json
Updated package-lock.json using `npm audit fix` (no other changes).
=> Security update 2022-04

vis/js/templates/modals/CitationModal.jsx, vis/js/templates/modals/EmbedModal.jsx, vis/js/utils/string.js
Please merge this together with [project-website PR 139](https://github.com/OpenKnowledgeMaps/project-website/pull/139) and [search-flow PR 29](https://github.com/OpenKnowledgeMaps/search-flow/pull/29).
Minor fixes in the Headstart UI.
=> Search Box MVP

CHANGELOG.md
- Fixed a few loopholes in the error handling logic of the backend (PR #672).
=> Biweekly release (22-07-14)

examples/local_triple/js/data-config_sg.js, vis/js/components/Footer.js, vis/js/reducers/modals.js, vis/js/templates/modals/infomodal/BaseInfo.jsx, vis/js/templates/modals/infomodal/subcomponents/StandardSGInfo.jsx
=> Links updates

docker-compose-phptest.yml, server/classes/headstart/tests/dbConnectionTest.php
This commit contains one test that covers a few of the different methods of the SQLite persistence class.
There are quite a few comments; not all tests need to be this verbose
=> Attempt to make an inital test that passes

package-lock.json, package.json
Security update: July 2023 - main updates package "babel-core": "^7.0.0-bridge.0"
=> Security update 2023 07

vis/js/dataprocessing/managers/DataManager.js, vis/js/templates/Paper.jsx, vis/js/templates/listentry/Details.jsx
make 15 authors in the map view and 20 in cites
=> Orcid bugfix

vis/js/templates/modals/infomodal/subcomponents/StandardKMInfo.jsx
=> Themes overviews

local_dev/config_local_headstart.ini, local_dev/searchflow-container/Dockerfile, server/classes/headstart/preprocessing/Snapshot.php, server/preprocessing/other-scripts/base.R, server/preprocessing/other-scripts/openaire.R, server/preprocessing/other-scripts/test/params_base.json, server/preprocessing/other-scripts/test/params_openaire.json, server/preprocessing/other-scripts/test/test_base.R, server/preprocessing/other-scripts/test/test_openaire.R, server/services/getChartSVG.js, server/services/snapshot/data-config_base.js, server/services/snapshot/headstart_snapshot.php, server/workers/api/src/apis/openaire.py
Bugfixes for
* OpenAIRE data cleanup for encoded greater/lesser than signs
* BASE title cleanup bug fix for bad regex
* snapshot bugfix
=> Bugfixes 2024 02

checks/config-js.sh, checks/ht-access.sh, docker-compose.yml, local-hotreload.sh, server/workers/base/Dockerfile
Changes:
- Added python3-dev dependency in the Dockerfile in the server/workers/base;
- Updated the Dockerfile in the Headstart;
- Updated the hotreload script: added a script that checks that the config.js presented;
- Updated the hotreload script: added a script that checks that the .htaccess file presented in the project-website, if not it will create one from the settings.htaccess file.
=> Deployment bugfixes
